version: "3.8"

services:
  faq-api:
    build: .
    container_name: faq-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db
      - redis-cache
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo-db:27017/faqdb
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
    driver: local
